app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email, Regexp, Length, EqualTo, ValidationError
from app.models import User


class RegisterForm(FlaskForm):
    '''
    用户注册表单
    '''
    username = StringField(
        label= "账号 ：",
        validators=[
            DataRequired("用户名不能为空！"),
            Length(min=3, max=50, message="用户名长度必须在3～10位之间")
        ],
        description="用户名",
        render_kw={
            "type":"text",
            "placeholder":"请输入用户名!",
            "class":"validate-username",
            "size":38,
        } 
    )
    phone = StringField(
        label="联系电话：",
        validators=[
            DataRequired("手机号不能为空！"),
            Regexp("1[34578][0-9]{9}", message="手机号码格式不正确")
        ],
        description="手机号",
        render_kw={
            "type":"text",
            "placeholder":"请输入联系电话！",
            "size":38,
        }
    )
    email = StringField(
        label="邮箱：",
        validators=[
            DataRequired("邮箱不能为空！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "tpye":"email",
            "placeholder":"请输入邮箱！",
            "size":38,
        }
    )
    password = PasswordField(
        label="密码：",
        validators=[
            DataRequired("密码不能为空")
        ],
        description="密码",
        render_kw={
            "placeholder": "请输入密码！",
            "size": 38,
        }
    )
    repassword = PasswordField(
        label="确认密码：",
        validators=[
            DataRequired("请输入正确密码"),
            EqualTo("password", message="两次密码不一致"),
        ],
        description="确认密码",
        render_kw={
            "placeholder":"请输入正确密码！",
            "size":38,
        }           
    )
    submit = SubmitField(
        label="同意协议并注册",
        render_kw = {
            "class":"btn btn-primary login",
        }
    )

    def validate_email(self, field):
        """
        检测注册邮箱是否已经存在
        """
        email = field.data
        user = User.query.filter_by(email = email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在！")
    
    def validate_phone(self, field):
        '''
        判断手机号是否存在
        '''
        phone = field.data
        user = User.query.filter_by(phone = phone).count()
        if user == 1:
            raise ValidationError("手机号已经存在！")


class LoginFrom(FlaskForm):
    '''
    登录功能
    '''
    username = StringField(
        validators=[

        ]
    )
    password = PasswordField()

    verify_code = StringField()

    submit = SubmitField()

class PasswordForm(FlaskForm):
    pass

class Suge

app/home/__init__.py
# _*_ coding:utf-8 _*_
from flask import Blueprint

# 创建蓝图
home = Blueprint("home", __name__)

import app.home.views

app/home/views.py
from . import home
from app import db
from app.home.forms import RegisterForm
from flask import render_template, url_for, redirect, session
from werkzeug.security import generate_password_hash


@home.route("/")
def index():
    return render_template('home/index.html')

@home.route("/register/", methods=["GET", "POST"])
def register():
    '''
    注册功能
    '''
    if "user_id" in session:
        return redirect(url_for("home.index"))
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            username = data["username"],
            email = data["email"],
            password = generate_password_hash(data["password"]),
            phone = data["phone"]
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("home.index"))
    return render_template("home/register.html", form=form)

@home.route("/login/", methods=["GET", "POST"])
def login():
    return "login"

app/templates/home/common.html
<!-- header start -->
{% include "home/header.html" %}
<!-- header end-->


<!-- content start-->
{% block content %}

{% endblock %}
<!-- content end -->


<!-- footer start-->
{% include "home/footer.html" %}
<!-- footer end-->

app/templates/home/footer.html
	<!-- 版权栏 -->

    <div class="container" style="margin-top:30px;border-top: 1px solid #D9D9D9;">
        <div id="footer">
        <dl class="foot">
            <dt>购物指南</dt>
            <dd>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">购物流程</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">会员介绍</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">生活旅行/团购</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">常见问题</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="nofollow">联系客服</a>
                </div>
            </dd>
        </dl>
        <dl class="foot">
            <dt>配送方式</dt>
            <dd>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">上门自提</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">物流限时达</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">配送服务查询</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">配送费收取标准</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">海外配送</a>
                </div>
            </dd>
        </dl>
        <dl class="foot">
            <dt>支付方式</dt>
            <dd>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">货到付款</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">在线支付</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">分期付款</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">邮局汇款</a>
                </div>
                <div>
                    <a href="#" target="_blank" rel="stylesheet">公司转账</a>
                </div>
            </dd>
        </dl>
            <dl class="foot">
                <dt>售后服务</dt>
                <dd>
                    <div>
                        <a href="#" target="_blank" rel="stylesheet">售后服务</a>
                    </div>
                    <div>
                        <a href="#" target="_blank" rel="stylesheet">价格保护</a>
                    </div>
                    <div>
                        <a href="#" target="_blank" rel="stylesheet">退款说明</a>
                    </div>
                    <div>
                        <a href="#" target="_blank" rel="stylesheet">返修退换货</a>
                    </div>
                    <div>
                        <a href="#" target="_blank" rel="stylesheet">取消订单</a>
                    </div>
                </dd>
            </dl>
            <dl class="foot">
                <dt>特色服务</dt>
                <dd>
                    <div>
                        <a href="http://www.mingrisoft.com/" target="_blank" rel="stylesheet">明日学院</a>
                    </div>
                    <div>
                        <a href="http://www.mingribook.com/" target="_blank" rel="stylesheet">明日图书</a>
                    </div>
                    <div>
                        <a href="http://www.mrbccd.com/" target="_blank" rel="stylesheet">明日编程词典</a>
                    </div>
                    <div>
                        <a href="http://mrbccd.taobao.com/" target="_blank" rel="stylesheet">明日淘宝店铺</a>
                    </div>
                </dd>
            </dl>
            <dl class="foot">
                <dt>关于我们</dt>
                <dd>
                    <img src="{{url_for('static',filename='home/images/qrcode.png')}}" alt="微信公众号">
                    <span>微信公众号</span>
                </dd>
            </dl>
        </div>
    </div>
    <footer id="mr-footer" class="wrap mr-footer">
        <section class="mr-copyright">
            <div class="container">
                <div style="width:auto; height:auto; margin:auto;">
                    <small> Copyright &copy;&nbsp;<a
                        href="http://www.mingrisoft.com/" target="_blank">吉林省明日科技有限公司</a> <a
                        href="{{url_for('admin.login')}}">后台</a> | 公司邮箱：<a
                        href="mailto:mingrisoft@mingrisoft.com">mingrisoft@mingrisoft.com</a>
                        &nbsp;&nbsp;电话：400-675-1066 | 公司地址：吉林省长春市卫星广场财富领域5A15室
                    </small> 吉ICP备 10002740号-2 吉公网安备22010202000132号
                </div>
            </div>
        </section>
    </footer>

app/templates/home/header.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>首页-商城</title>
<link rel="stylesheet" href="{{url_for('static',filename='home/css/mr-01.css')}}" type="text/css">
<script src="{{url_for('static',filename='home/js/jsArr01.js')}}" type="text/javascript"></script>
<script src="{{url_for('static',filename='home/js/module.js')}}" type="text/javascript"></script>
<script src="{{url_for('static',filename='home/js/jsArr02.js')}}" type="text/javascript"></script>
<script src="{{url_for('static',filename='home/js/tab.js')}}" type="text/javascript"></script>
</head>

<body>
<div id="toolbar" style="background-color: #F0F0F0; width: 100%;">
	<div class="container">
		<div class="row">
			<div class="toolbar-ct-1">
				<p>
					<i class="fa fa-phone"></i>
					<span style="margin-right: 15px;">电话：400-675-1066</span>
					{% if "user_id" in session %}
						您好，{{session['username']}}
						&nbsp; &nbsp;<a href="{{url_for('home.modify_password')}}">修改</a>&nbsp;&nbsp;
						|&nbsp;&nbsp;<a href="{{url_for('home.logout')}}">退出</a>
					{% else %}
						<a  href="{{url_for('home.login')}}">登录</a>&nbsp; ｜ &nbsp;<a href="{{url_for('home.register')}}">注册</a>
					{% endif %}
				</p>
			</div>
			<div class="toolbar-ct-2">
				<a href="{{url_for('home.order_list')}}">我的订单</a>&nbsp;&nbsp; | &nbsp;&nbsp; 我的收藏
			</div>
		</div>
	</div>
	<div style="background-color: white; width: 100%">
		<div class="container">
			<div class="row">
				<div class="toolbar-ct col-xs-12 col-md-6  hidden-sm hidden-xs">
					<div class="toolbar-ct-1">
						<img src="{{url_for('static',filename='home/images/51logo.png')}}">
					</div>
					<div>
						<!-- 搜索条 -->
						<div class="search_box">
							<div class="top-nav-search">
								<form method="get" action="{{url_for('home.goods_search')}}">
									<input type="text" name="keywords" size="38"
										style="border: 0px;" class="top-nav-search-input" placeholder="请输入内容" />
									<button type="submit" class="search_box_img" onFocus="this.blur()">
										<img src="{{url_for('static',filename='home/images/search.png')}}" alt="">
									</button>
								</form>
							</div>
						</div>
						<!-- //搜索条 -->
					</div>
				</div>
				<div class="toolbar-ct toolbar-ct-right col-xs-12 col-md-3">
					<div class="toolbar-ct-2 "
						style="margin-top: 35px; border: 1px solid #EAEAEA; padding: 5px;">
						<a href="{{url_for('home.shopping_cart')}}" style="color: #E33737; font-size: 20px;"><i
							class="fa fa-cart1"></i> 我的购物车</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- 网站头部 -->
<header id="mr-header" class="wrap mr-header">
	<div class="container">
		<div class="row">
			<!-- //网站Logo -->
			<!-- 主导航条 -->
			<nav id="mr-mainnav"
				class="col-xs-12 col-md-6 mr-mainnav navbar navbar-default">
				<div class="mr-navbar navbar-collapse collapse">
					<div class="mr-megamenu animate slide" data-duration="400"
						data-responsive="true">
						<ul class="nav navbar-nav level0">
							<li itemprop="name" data-id="435" data-level="1">
								<a id="index" itemprop="url" class="" href="{{url_for('home.index')}}"data-target="#">
									首页
								</a>
							</li>
							<li itemprop="name" data-id="510" data-level="1">
								<!--<a id="jingying" itemprop="url" class="" href="{{url_for('home.goods_list',supercat_id=14)}}" data-target="#">-->
								<a id="jingying" itemprop="url" class="" href="/goods_list/14?type=14" data-target="#">
									图书类
								</a>
							</li>
							<li itemprop="name" data-id="510" data-level="1">
								<a id="wenyi" itemprop="url" class="" href="/goods_list/15?type=15"
								data-target="#">家电类</a>
							</li>

							<li itemprop="name" data-id="510" data-level="1">
								<a id="jiaoyu" itemprop="url" class="" href="/goods_list/16?type=16"
								data-target="#">服装类</a>
							</li>
							<li itemprop="name" data-id="510" data-level="1">
								<a id="shenghuo" itemprop="url" class="" href="/goods_list/17?type=17"
								   data-target="#">电子类
								</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			<!-- //主导航条 -->
		</div>
	</div>
</header>
<script>
	// 获取页面参数
	function GetString(name) {
		var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)");//正则表达式
		var r = window.location.search.substr(1).match(reg);//获取鼠标点击区域
		if (r != null)
			return unescape(r[2]);//返回区域编号
		return null;
	}
	var type = GetString('type');
	if (type === '14') {
		var jingying = document.getElementById('jingying');
		jingying.style.backgroundColor = "#9E2626";

	}
	if (type === '15') {
		var wenyi = document.getElementById('wenyi');
		wenyi.style.backgroundColor = "#9E2626";

	}
	if (type === '16') {
		var jiaoyu = document.getElementById('jiaoyu');
		jiaoyu.style.backgroundColor = "#9E2626";

	}
	if (type === '17') {
		var shenghuo = document.getElementById('shenghuo');
		shenghuo.style.backgroundColor = "#9E2626";

	}
	if (type == null) {//默认登录无点击
		var index = document.getElementById('index');
		index.style.backgroundColor = "#9E2626";

	}
</script>
	<!-- //网站头部 -->

app/templates/home/index.html
{% extends "home/common.html" %}
{% block content %}
	<!-- 轮播广告及热门商品 -->
	<div class="container mr-sl mr-sl-1">
		<div class="mr-spotlight mr-spotlight-1  row">
			<!-- 显示轮播广告 -->
			<div
				class=" col-lg-9 col-md-12  col-sm-3 hidden-sm   col-xs-6 hidden-xs ">
				<div class="mr-module module " id="Mod159">
					<div class="module-inner">
						<div class="module-ct">
							<div class="mijoshop">
								<div class="container_oc">
									<div class="slideshow">
										<div id="slidershow" class="nivoSlider">
											<a href="#" class="nivo-imageLink" style="display: block;cursor:default">
												<img src="{{url_for('static',filename='images/banner/img1.png')}}" class="img-responsive"
												style="display: none;">
											</a>
											<a href="#"
												class="nivo-imageLink" style="display: none;cursor:default">
											<img src="{{url_for('static',filename='images/banner/img2.png')}}" class="img-responsive"
												style="display: none;">
											</a>
											<a href="#" class="nivo-imageLink" style="display: none;cursor:default">
												<img src="{{url_for('static',filename='images/banner/img3.png')}}" class="img-responsive"
												style="display: none;">
											</a>
										</div>
									</div>
									<script type="text/javascript">
										//实现调用幻灯片插件轮播广告
										jQuery(document).ready(function() {
											jQuery('#slidershow').nivoSlider();
										});
									</script>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- 显示热门商品 -->
			<div class="col-lg-3  col-md-6 hidden-md   col-sm-3 hidden-sm   col-xs-6 hidden-xs ">
				<div class="mr-module module highlight " id="Mod160">
					<div class="module-inner">
						<h3 class="module-title ">
							<span>热门商品</span>
						</h3>
						<div class="module-ct">
							<div class="mijoshop">
								<div class="container_oc">
									<div class="box_oc">
										<!-- 循环显示热门商品 ：添加两条商品信息-->
										{% for item in hot_goods %}
										<div class="box-product product-grid">
											<div>
												<div class="image">
													<a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}">
														<img src="{{url_for('static',filename='images/goods/'+item.picture)}}" width="250px">
													</a>
												</div>
												<div class="name">
													<a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}">{{item.name}}</a>
												</div>
												<!-- 星级评分条 -->
												<div class="rating">
													<span class="fa fa-stack"><i
														class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i> </span> <span
														class="fa fa-stack"><i
														class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i> </span> <span
														class="fa fa-stack"><i
														class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i> </span> <span
														class="fa fa-stack"><i
														class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i> </span> <span
														class="fa fa-stack"><i
														class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i> </span>
												</div>
												<!-- // 星级评分条 -->
												<!-- 商品价格 -->
												<div class="price">
													<span class="price-new">价格：{{item.current_price}} 元</span>
												</div>
												<!-- // 商品价格 -->
											</div>
										</div>
										{% endfor %}
										<!-- // 循环显示热门商品 ：添加两条商品信息-->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- // 显示热门商品 -->
		</div>
	</div>
	<!-- //轮播广告及热门商品  -->
	<!-- 最新上架及打折商品展示 -->
	<nav class="container mr-masstop  hidden-sm hidden-xs">
	<div class="custom">
		<div>
			<div class="ja-tabswrap default" style="width: 100%;">
				<div id="myTab" class="container">
					<h3 class="index_h3">
						<span class="index_title">最新上架</span>
					</h3>
					<!-- //最新上架选项卡 -->
					<div class="ja-tab-content ja-tab-content col-6 active"
						style="opacity: 1; width: 100%; visibility: visible;">
						<div class="ja-tab-subcontent">
							<div class="mijoshop">
								<div class="container_oc">
									<div class="row">
										<!-- 循环显示最新上架商品 ：添加12条商品信息-->
										{% for item in new_goods %}
										<div class="product-grid col-lg-2 col-md-3 col-sm-6 col-xs-12">
											<div class="product-thumb transition">
												<div class="actions">
													<div class="image">
														<a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}">
															<img src="{{url_for('static',filename='images/goods/'+item.picture)}}" alt="{{item.name}}" class="img-responsive">
														</a>
													</div>
													<div class="button-group">
														<div class="cart">
															<button class="btn btn-primary btn-primary" type="button"
																data-toggle="tooltip"
																onclick='javascript:window.location.href="/cart_add/?goods_id={{item.id}}&number=1"; '
																style="display: none; width: 33.3333%;"
																data-original-title="加入到购物车">
																<i class="fa fa-shopping-cart"></i>
															</button>
														</div>
													</div>
												</div>
												<div class="caption">
													<div class="name" style="height: 40px">
														<a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}">
															{{item.name}}
														</a>
													</div>
													<p class="price">
														价格：{{item.current_price}}元
													</p>
												</div>
											</div>
										</div>
										{% endfor %}
										
										<!-- //循环显示最新上架商品：添加12条商品信息 -->
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- //最新上架选项卡 -->
					<!-- 打折商品选项卡 -->
					<h3 class="index_h3"><span class="index_title">打折商品</span></h3>
					<div class="ja-tab-subcontent">
						<div class="mijoshop">
							<div class="container_oc">
								<div class="row">
									<!-- 循环显示打折商品 ：添加12条商品信息-->
									{% for item in sale_goods %}
									<div class="product-grid col-lg-2 col-md-3 col-sm-6 col-xs-12">
										<div class="product-thumb transition">
											<div class="actions">
												<div class="image">
													<a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}">
														<img src="{{url_for('static',filename='images/goods/'+item.picture)}}"
															 alt="{{item.name}}" class="img-responsive">
													</a>
												</div>
												<div class="button-group">
													<div class="cart">
														<button class="btn btn-primary btn-primary" type="button"
															data-toggle="tooltip"
															onclick='javascript:window.location.href="/cart_add/?goods_id={{item.id}}&number=1"; '
															style="display: none; width: 33.3333%;"
															data-original-title="加入到购物车">
															<i class="fa fa-shopping-cart"></i>
														</button>
													</div>
												</div>
											</div>
											<div class="caption">
												<div class="name" style="height: 40px">
													<a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}" style="width: 95%">
														{{item.name}}</a>
												</div>
												<div class="name" style="margin-top: 10px">
													<span style="color: #0885B1">分类：</span>{{item.subcat.cat_name}}
												</div>
												<span class="price"> 现价：{{item.current_price}} 元
												</span><br> <span class="oldprice">原价：{{item.original_price}}元
												</span>
											</div>
										</div>
									</div>
									{% endfor %}
									<!-- 循环显示打折商品 ：添加12条商品信息-->
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- //打折商品 选项卡-->
			</div>
		</div>
	</div>
	</nav>
<!-- //版权栏 -->
{% endblock %}

app/templates/home/register.html
<!DOCTYPE html>
<html >
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>注册</title>
<link rel="stylesheet" href="{{url_for('static',filename='home/css/mr-01.css')}}" type="text/css">
</head>
<body>
	<!-- 主体内容 -->
	<div id="mr-mainbody" class="container mr-mainbody">
		<div class="row">
			<div id="mr-content" class="mr-content col-xs-12">
				<div class="login-wrap"
					style="margin-bottom: 60px; margin-top: 50px">
					<!-- <div style="max-width: 540px; margin: 0 auto;">
						<a href="index.html" title="点击返回首页">
							<img src="{{url_for('static',filename='home/images/51logo.png')}}"></a>
					</div> -->
					<div class="login">
						<div class="page-header" style="pause: 0px;">
							<h1 class="login_h1">会员注册</h1>
						</div>
						<!-- 会员注册表单 -->
						<form  action="" method="post" class="form-horizontal">
							<fieldset>
								<!-- 用户名 -->
								<div class="form-group">
									<div class="col-sm-4 control-label">
										{{form.username.label}}
									</div>
									<div class="col-sm-8">
										<!-- 账户文本框 -->
										{{form.username}}
										{% for err in form.username.errors %}
										<span class="error">{{ err }}</span>
										{% endfor %}
									</div>
								</div>
								<!-- 密码框 -->
								<div class="form-group">
									<div class="col-sm-4 control-label">
										{{form.password.label}}
									</div>
									<div class="col-sm-8">
										<!-- 密码文本框 -->
										{{form.password}}
										{% for err in form.password.errors %}
										<span class="error">{{ err }}</span>
										{% endfor %}
									</div>
								</div>
								<!-- 重复密码框 -->
								<div class="form-group">
									<div class="col-sm-4 control-label">
										{{form.repassword.label}}
									</div>
									<div class="col-sm-8">
										<!-- 确认密码文本框 -->
										{{form.repassword}}
										{% for err in form.repassword.errors %}
										<span class="error">{{ err }}</span>
										{% endfor %}
									</div>
								</div>
								<!-- 手机号码 -->
								<div class="form-group">
									<div class="col-sm-4 control-label">
										{{form.phone.label}}
									</div>
									<div class="col-sm-8" style="clear: none;">
										<!-- 输入联系电话的文本框 -->
										{{form.phone}}
										{% for err in form.phone.errors %}
										<span class="error">{{ err }}</span>
										{% endfor %}
									</div>
								</div>
								<!-- 邮件 -->
								<div class="form-group">
									<div class="col-sm-4 control-label">
										{{form.email.label}}
									</div>
									<div class="col-sm-8" style="clear: none;">
										<!-- 输入邮箱的文本框 -->
										{{form.email}}
										{% for err in form.email.errors %}
										<span class="error">{{ err }}</span>
										{% endfor %}
									</div>
								</div>
								<div class="form-group">
									<div style="float: right; padding-right: 280px;">
										<!-- **商城 --><a href="#" style="color: #0885B1;">《使用条款》</a>
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-offset-4 col-sm-8">
										{{ form.csrf_token }}
										{{ form.submit }}
									</div>
								</div>
								<div class="form-group" style="margin: 20px;">
									<label
										style="float: right; color: #858585; margin-right: 80px; margin-top: 10px; font-size: 14px;">已有账号！<a
										href="{{url_for('home.login')}}">去登录</a></label>
								</div>
							</fieldset>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //主体内容 -->
</body>
</html>